# Generated by Django 5.2.4 on 2025-07-15 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='value',
            new_name='score',
        ),
    ]
